### ISSUE TITLE
Pathlib

### ISSUE THREAD

**Issue by luciodaou** [saviobatista/siros#3]
https://github.com/saviobatista/siros/blob/376099237b100c1b6616d5732e4c134fd5814387/lib/siros_parser.py#L2

O módulo `pathlib` deve ser instalado através do comando `pip install pathlib2` e ainda assim, é um pacote que consta como sem atualizações a partir de janeiro de 2020. 

https://pypi.org/project/pathlib2/

**Comment by saviobatista** [comment]
De acordo, devido a "lazy programming" foi usado o método mais simplista, ajustado no commit (0856250a7916b623629f55c92bb636f29b7c40ac) para utilizar a biblioteca `os` já amplamente utilizada no restante.
